import type { TSubtypeGroup, TTypeGroup } from '../types'

type TApplicationSubtype =
  | 'atomXml'
  | 'atomcatXml'
  | 'ecmascript'
  | 'epubZip'
  | 'gzip'
  | 'javaArchive'
  | 'javascript'
  | 'json'
  | 'ldJson'
  | 'mp4'
  | 'msword'
  | 'octetStream'
  | 'ogg'
  | 'pdf'
  | 'pkcs10'
  | 'pkcs7Mime'
  | 'pkcs7Signature'
  | 'pkcs8'
  | 'postscript'
  | 'rdfXml'
  | 'rssXml'
  | 'rtf'
  | 'smilXml'
  | 'vndAmazonEbook'
  | 'vndAppleInstallerXml'
  | 'vndMozillaXulXml'
  | 'vndMsExcel'
  | 'vndMsFontobject'
  | 'vndMsPowerpoint'
  | 'vndOasisOpendocumentPresentation'
  | 'vndOasisOpendocumentSpreadsheet'
  | 'vndOasisOpendocumentText'
  | 'vndOpenxmlformatsOfficedocumentPresentationmlPresentation'
  | 'vndOpenxmlformatsOfficedocumentSpreadsheetmlSheet'
  | 'vndOpenxmlformatsOfficedocumentWordprocessingmlDocument'
  | 'vndRar'
  | 'vndVisio'
  | 'x7zCompressed'
  | 'xAbiword'
  | 'xBzip'
  | 'xBzip2'
  | 'xCdf'
  | 'xCsh'
  | 'xFontOff'
  | 'xFreearc'
  | 'xhtmlXml'
  | 'xHttpdPhp'
  | 'xml'
  | 'xmlDtd'
  | 'xPkcs12'
  | 'xSh'
  | 'xShockwaveFlash'
  | 'xSilverlightApp'
  | 'xsltXml'
  | 'xTar'
  | 'xWwwFormUrlencoded'
  | 'zip'

type TApplicationSubtypeGroup = TSubtypeGroup<TApplicationSubtype>
type TApplicationTypeGroup = TTypeGroup<'application', TApplicationSubtype>

export type {
  TApplicationSubtype,
  TApplicationSubtypeGroup,
  TApplicationTypeGroup
}
